services:
  laravel-madefy:
    container_name: laravel-madefy
    build: .
    volumes:
      - ./laravel-app:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 9000:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks
    ports:
      - 3306:3306
